baseURL = "https://joseph-montanez.github.io/puncture-website/"
languageCode = "en-us"
title = "Puncture"
theme = "terrassa"
publishDir = "docs"


[params.hero]
    textColor = "#fff" # Empty for default color